if(NOT DEFINED DEFAULT_TARGET_ARCH)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64")
        set(DEFAULT_TARGET_ARCH "x64")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|ARM64")
        set(DEFAULT_TARGET_ARCH "arm64")
    else()
        message(FATAL_ERROR "Unsupported host processor: ${CMAKE_SYSTEM_PROCESSOR}. "
                "Please define DEFAULT_TARGET_ARCH explicitly (x64, arm64)")
    endif()
endif()

if(NOT DEFINED SUPPORTED_ARCHITECTURES)
    set(SUPPORTED_ARCHITECTURES "x86;x64;arm64")
endif()

set(TARGET_ARCH ${DEFAULT_TARGET_ARCH} CACHE STRING "Target architecture")

set_property(CACHE TARGET_ARCH PROPERTY STRINGS ${SUPPORTED_ARCHITECTURES})

if(NOT TARGET_ARCH IN_LIST SUPPORTED_ARCHITECTURES)
    message(FATAL_ERROR "Unsupported architecture: ${TARGET_ARCH}. Supported: ${SUPPORTED_ARCHITECTURES}")
endif()